---
- hosts: all
  roles:
    - pulp3-postgresql
    - pulp3-workers
    - pulp3-resource-manager
    - pulp3-webserver
    - pulp3-content
  environment:
    DJANGO_SETTINGS_MODULE: pulpcore.app.settings
